# vue deployer
public_dir: dist

deploy:
  type: git
  repo:
    github:
      url: https://github.com/Cenergy/vue-map.git
      branch: master
    coding:
      url: https://e.coding.net/aigis/map.git
      branch: master
    aigisss:
      url: root@aigisss:/home/git/gis
      branch: master
