# vue deployer
public_dir: dist

deploy:
  type: git
  repo:
    github: 
      url: https://github.com/Cenergy/vue-map.git
      branch: master
    coding: 
      url: https://git.dev.tencent.com/AIGIS/vue-map.git
      branch: master
